<?php

namespace ContainerEGoJUhx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X7Sq9SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x7_sq9S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x7_sq9S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartManager' => ['privates', 'App\\Manager\\CartManager', 'getCartManagerService', true],
            'commandesFactory' => ['services', 'App\\Factory\\CommandesFactory', 'getCommandesFactoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cartManager' => 'App\\Manager\\CartManager',
            'commandesFactory' => 'App\\Factory\\CommandesFactory',
            'entityManager' => '?',
        ]);
    }
}
