<?php

namespace ContainerLf4saxO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.JI6ffAS.App\Entity\Commandes' shared service.
     *
     * @return \App\Entity\Commandes
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.JI6ffAS": it references class "App\\Entity\\Commandes" but no such service exists.');
    }
}
