<?php

namespace ContainerVxSCVXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartManagerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Manager\CartManager' shared autowired service.
     *
     * @return \App\Manager\CartManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Manager/CartManager.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/CommandesFactory.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['App\\Manager\\CartManager'])) {
            return $container->privates['App\\Manager\\CartManager'];
        }

        return $container->privates['App\\Manager\\CartManager'] = new \App\Manager\CartManager(($container->privates['App\\Storage\\CartSessionStorage'] ?? $container->load('getCartSessionStorageService')), ($container->privates['App\\Factory\\CommandesFactory'] ?? ($container->privates['App\\Factory\\CommandesFactory'] = new \App\Factory\CommandesFactory())), $a);
    }
}
