<?php

namespace ContainerVxSCVXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveExpiredCartsCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\RemoveExpiredCartsCommand' shared autowired service.
     *
     * @return \App\Command\RemoveExpiredCartsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/RemoveExpiredCartsCommand.php';

        $container->privates['App\\Command\\RemoveExpiredCartsCommand'] = $instance = new \App\Command\RemoveExpiredCartsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\CommandesRepository'] ?? $container->load('getCommandesRepositoryService')));

        $instance->setName('app:remove-expired-carts');

        return $instance;
    }
}
