<?php

namespace ContainerAuKULOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveCartItemListenerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\EventListener\RemoveCartItemListener' shared autowired service.
     *
     * @return \App\Form\EventListener\RemoveCartItemListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Form/EventListener/RemoveCartItemListener.php';

        return $container->privates['App\\Form\\EventListener\\RemoveCartItemListener'] = new \App\Form\EventListener\RemoveCartItemListener();
    }
}
