<?php

namespace ContainerDJzeNCx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JI6ffASService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JI6ffAS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JI6ffAS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'order' => ['privates', '.errored..service_locator.JI6ffAS.App\\Entity\\Commandes', NULL, 'Cannot autowire service ".service_locator.JI6ffAS": it references class "App\\Entity\\Commandes" but no such service exists.'],
        ], [
            'order' => 'App\\Entity\\Commandes',
        ]);
    }
}
