<?php

namespace ContainerJBRCDpN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V15EBJBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v15EBJB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v15EBJB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['services', '.container.private.security.password_encoder', 'get_Container_Private_Security_PasswordEncoderService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'utilisateur' => ['privates', '.errored..service_locator.v15EBJB.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.v15EBJB": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
        ], [
            'encoder' => '?',
            'entityManager' => '?',
            'utilisateur' => 'App\\Entity\\Utilisateur',
        ]);
    }
}
