<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAuKULOs\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAuKULOs/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerAuKULOs.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerAuKULOs\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerAuKULOs\App_KernelTestDebugContainer([
    'container.build_hash' => 'AuKULOs',
    'container.build_id' => '8a4b9fdf',
    'container.build_time' => 1684953738,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAuKULOs');
