<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxSCVXr\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxSCVXr/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerVxSCVXr.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerVxSCVXr\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerVxSCVXr\App_KernelTestDebugContainer([
    'container.build_hash' => 'VxSCVXr',
    'container.build_id' => 'f447d8be',
    'container.build_time' => 1684869100,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxSCVXr');
