<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFpIL97Z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFpIL97Z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFpIL97Z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFpIL97Z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFpIL97Z\App_KernelDevDebugContainer([
    'container.build_hash' => 'FpIL97Z',
    'container.build_id' => 'f8813ef4',
    'container.build_time' => 1681285708,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFpIL97Z');
