<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAzowPWI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAzowPWI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAzowPWI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAzowPWI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAzowPWI\App_KernelDevDebugContainer([
    'container.build_hash' => 'AzowPWI',
    'container.build_id' => '18a14eef',
    'container.build_time' => 1680183670,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAzowPWI');
