<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVAEsWj9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVAEsWj9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVAEsWj9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVAEsWj9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVAEsWj9\App_KernelDevDebugContainer([
    'container.build_hash' => 'VAEsWj9',
    'container.build_id' => '9fa4de32',
    'container.build_time' => 1681299296,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVAEsWj9');
